--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: jenkins
  name: jenkins
spec: 
  containers: 
    - 
      image: bharathnoddy/jenkins-docker
      name: jenkins
      ports: 
        - 
          containerPort: 8080
      volumeMounts: 
        - 
          mountPath: /var/run/docker.sock
          name: socket
  volumes: 
    - 
      hostPath: 
        path: /var/run/docker.sock
      name: socket



--- 
apiVersion: v1
kind: Service
metadata: 
  name: jenkins
spec: 
  ports: 
    - 
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector: 
    app: jenkins
  type: LoadBalancer

